EntrecineWebApp/Models/Sesion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrecineWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public Sesion()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int DescuentoId { get; set; }
        public int SalaId { get; set; }
        public int PeliculaId { get; set; }
    
        public virtual Descuento Descuento { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual Sala Sala { get; set; }
    }
}

EntrecineWebApp/Controllers/SesionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntrecineWebApp.Models;
using EntrecineWebApp.Shared;

namespace EntrecineWebApp.Controllers
{
    public class SesionController : Controller
    {
        private EntrecineModelContainer db = new EntrecineModelContainer();

        //
        // GET: /Sesion/
        public ActionResult Index()
        {
            var sesionconjunto = db.SesionConjunto.Include(s => s.Descuento).Include(s => s.Pelicula).Include(s => s.Sala);

            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(sesionconjunto.ToList()), RedirectToAction("Index", "Home"));
        }


        //
        // GET: /Sesion/Crear
        public ActionResult Crear()
        {

            ViewBag.DescuentoId = new SelectList(db.DescuentoConjunto, "Id", "Nombre");
            ViewBag.PeliculaId = new SelectList(db.PeliculaConjunto, "Id", "Nombre");
            ViewBag.SalaId = new SelectList(db.SalaConjunto, "Id", "Id");

            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(), RedirectToAction("Index", "Home"));            
        }

        //
        // POST: /Sesion/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Sesion sesion)
        {
            if (ModelState.IsValid)
            {
                db.SesionConjunto.Add(sesion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DescuentoId = new SelectList(db.DescuentoConjunto, "Id", "Nombre", sesion.DescuentoId);
            ViewBag.PeliculaId = new SelectList(db.PeliculaConjunto, "Id", "Nombre", sesion.PeliculaId);
            ViewBag.SalaId = new SelectList(db.SalaConjunto, "Id", "Id", sesion.SalaId);

            return View(sesion);
        }

        //
        // GET: /Sesion/Editar/5
        public ActionResult Editar(int id = 0)
        {
            Sesion sesion = db.SesionConjunto.Find(id);
            if (sesion == null)
            {
                return HttpNotFound();
            }

            ViewBag.DescuentoId = new SelectList(db.DescuentoConjunto, "Id", "Nombre", sesion.DescuentoId);
            ViewBag.PeliculaId = new SelectList(db.PeliculaConjunto, "Id", "Nombre", sesion.PeliculaId);
            ViewBag.SalaId = new SelectList(db.SalaConjunto, "Id", "Id", sesion.SalaId);
            
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(sesion), RedirectToAction("Index", "Home"));
        }

        //
        // POST: /Sesion/Editar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Sesion sesion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sesion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DescuentoId = new SelectList(db.DescuentoConjunto, "Id", "Nombre", sesion.DescuentoId);
            ViewBag.PeliculaId = new SelectList(db.PeliculaConjunto, "Id", "Nombre", sesion.PeliculaId);
            ViewBag.SalaId = new SelectList(db.SalaConjunto, "Id", "Id", sesion.SalaId);

            return View(sesion);
        }

        //
        // GET: /Sesion/Borrar/5
        public ActionResult Borrar(int id = 0)
        {
            Sesion sesion = db.SesionConjunto.Find(id);
            
            if (sesion == null)
            {
                return HttpNotFound();
            }

            return Seguridad.ComprobarAdministrador(db, User.Identity.Name,View(sesion), RedirectToAction("Index", "Home"));
        }

        //
        // POST: /Sesion/Borrar/5
        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sesion sesion = db.SesionConjunto.Find(id);
            db.SesionConjunto.Remove(sesion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EntrecineWebApp/Views/Sesion/Borrar.cshtml
@model EntrecineWebApp.Models.Sesion

@{
    ViewBag.Title = "Delete";
}

<h2>Borrado de sesión</h2>

<h3>¿Estás seguro de realizar el borrado de la sesión?</h3>
<fieldset>
    <legend>Sesion</legend>

    <div class="display-label">
         @Html.LabelFor(model => model.PrecioCalculado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrecioCalculado)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Descuento.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descuento.Nombre)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Sala.Id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sala.Id)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Pelicula.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pelicula.Nombre)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver", "Index")
    </p>
}

EntrecineWebApp/Views/Sesion/Crear.cshtml
@model EntrecineWebApp.Models.Sesion

@{
    ViewBag.Title = "Crear sesión";
}

<h2>Crear sesión</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sesion</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DescuentoId, "Descuento")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DescuentoId", String.Empty)
            @Html.ValidationMessageFor(model => model.DescuentoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SalaId, "Sala")
        </div>
        <div class="editor-field">
            @Html.DropDownList("SalaId", String.Empty)
            @Html.ValidationMessageFor(model => model.SalaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PeliculaId, "Pelicula")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PeliculaId", String.Empty)
            @Html.ValidationMessageFor(model => model.PeliculaId)
        </div>

        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Sesion/Create.cshtml
@model EntrecineWebApp.Models.Sesion

@{
    ViewBag.Title = "Create";
}

<h2>Creación sesión</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sesion</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DescuentoId, "Descuento")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DescuentoId", String.Empty)
            @Html.ValidationMessageFor(model => model.DescuentoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SalaId, "Sala")
        </div>
        <div class="editor-field">
            @Html.DropDownList("SalaId", String.Empty)
            @Html.ValidationMessageFor(model => model.SalaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PeliculaId, "Pelicula")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PeliculaId", String.Empty)
            @Html.ValidationMessageFor(model => model.PeliculaId)
        </div>

        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Sesion/Delete.cshtml
@model EntrecineWebApp.Models.Sesion

@{
    ViewBag.Title = "Delete";
}

<h2>Borrado de sesión</h2>

<h3>¿Estás seguro de realizar el borrado de la sesión?</h3>
<fieldset>
    <legend>Sesion</legend>

    <div class="display-label">
         @Html.LabelFor(model => model.PrecioCalculado)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PrecioCalculado)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Descuento.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descuento.Nombre)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Sala.Id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sala.Id)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Pelicula.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Pelicula.Nombre)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver", "Index")
    </p>
}

EntrecineWebApp/Views/Sesion/Edit.cshtml
@model EntrecineWebApp.Models.Sesion

@{
    ViewBag.Title = "Edición de sesiones";
}

<h2>Editar sesión</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sesion</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DescuentoId, "Descuento")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DescuentoId", String.Empty)
            @Html.ValidationMessageFor(model => model.DescuentoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SalaId, "Sala")
        </div>
        <div class="editor-field">
            @Html.DropDownList("SalaId", String.Empty)
            @Html.ValidationMessageFor(model => model.SalaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PeliculaId, "Película")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PeliculaId", String.Empty)
            @Html.ValidationMessageFor(model => model.PeliculaId)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Sesion/Editar.cshtml
@model EntrecineWebApp.Models.Sesion

@{
    ViewBag.Title = "Edición de sesiones";
}

<h2>Editar sesión</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Sesion</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DescuentoId, "Descuento")
        </div>
        <div class="editor-field">
            @Html.DropDownList("DescuentoId", String.Empty)
            @Html.ValidationMessageFor(model => model.DescuentoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SalaId, "Sala")
        </div>
        <div class="editor-field">
            @Html.DropDownList("SalaId", String.Empty)
            @Html.ValidationMessageFor(model => model.SalaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PeliculaId, "Película")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PeliculaId", String.Empty)
            @Html.ValidationMessageFor(model => model.PeliculaId)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Sesion/Index.cshtml
@using EntrecineWebApp.Models
@model IEnumerable<EntrecineWebApp.Models.Sesion>

@{
    ViewBag.Title = "Editar Sesiones";
}

<h2>Edición de sesiones</h2>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SalaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pelicula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescuentoId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SalaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pelicula.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descuento.Porcentaje)%
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", "Sesion", new { id = item.Id }, new { }) |
            @Html.ActionLink("Borrar", "Borrar", "Sesion", new { id = item.Id }, new { })
        </td>
    </tr>
}

</table>