EntrecineWebApp/Models/Pelicula.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrecineWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public Pelicula()
        {
            this.Sesion = new HashSet<Sesion>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public int Duracion { get; set; }
    
        public virtual ICollection<Sesion> Sesion { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}

EntrecineWebApp/Controllers/PeliculaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntrecineWebApp.Models;
using EntrecineWebApp.Shared;

namespace EntrecineWebApp.Controllers
{
    public class PeliculaController : Controller
    {
        private EntrecineModelContainer db = new EntrecineModelContainer();

        //
        // GET: /Pelicula/Cartelera
        public ActionResult Cartelera()
        {
            return View(db.PeliculaConjunto.ToList());
        }

        //
        // GET: /Pelicula/Detalles/5
        public ActionResult Detalles(int id = 0)
        {
            Pelicula pelicula = db.PeliculaConjunto.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // GET: /Pelicula/
        public ActionResult Index()
        {
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(db.PeliculaConjunto.ToList()), RedirectToAction("Index", "Home"));
        }

        //
        // GET: /Pelicula/Crear
        public ActionResult Crear()
        {
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(), RedirectToAction("Index", "Home"));
            
        }

        //
        // POST: /Pelicula/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.PeliculaConjunto.Add(pelicula);
                db.SaveChanges();

                if (pelicula.Caratula != null && pelicula.Caratula.ContentLength > 0)
                {
                    var filename = "caratula_" + pelicula.Id + ".jpg";
                    var path = Path.Combine(Server.MapPath("~/Images/Caratulas"), filename);
                    pelicula.Caratula.SaveAs(path);
                }

                return RedirectToAction("Index","Home");
            }

            return View(pelicula);
        }

        //
        // GET: /Pelicula/Editar/5
        public ActionResult Editar(int id = 0)
        {
            Pelicula pelicula = db.PeliculaConjunto.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(pelicula), RedirectToAction("Index", "Home"));
        }

        //
        // POST: /Pelicula/Editar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

    }
}

EntrecineWebApp/Views/Pelicula/Cartelera.cshtml
@model IEnumerable<EntrecineWebApp.Models.Pelicula>

@{
    ViewBag.Title = "Cartelera";
}

<h2>Cartelera</h2>

<div id="cartelera">

    @foreach (var item in Model)
    {
            <div class="movieCartelera">
                <div class="titulo">@Html.DisplayFor(modelItem => item.Nombre)</div>
                <a href="@Url.Content("~/Pelicula/Detalles/"+item.Id)"><img src="@Url.Content("~/images/Caratulas/caratula_"+@Html.DisplayFor(modelItem=>item.Id)+".jpg")" /></a>
            </div>
            
    }

</div>

EntrecineWebApp/Views/Pelicula/Crear.cshtml
@model EntrecineWebApp.Models.Pelicula

@{
    ViewBag.Title = "Añadir Película";
}

<h2>Crear película</h2>

@using (Html.BeginForm("Crear", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Película</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Duracion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Duracion)
            @Html.ValidationMessageFor(model => model.Duracion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Caratula)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Caratula)
            @Html.ValidationMessageFor(model => model.Caratula)
        </div>

        <p>
            <input type="submit" value="Añadir Película" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Pelicula/Create.cshtml
@model EntrecineWebApp.Models.Pelicula

@{
    ViewBag.Title = "Añadir Película";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pelicula", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Película</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Duracion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Duracion)
            @Html.ValidationMessageFor(model => model.Duracion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Caratula)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Caratula)
            @Html.ValidationMessageFor(model => model.Caratula)
        </div>

        <p>
            <input type="submit" value="Añadir Película" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Pelicula/Details.cshtml
@using EntrecineWebApp.Views.Shared
@using EntrecineWebApp.Models
@model EntrecineWebApp.Models.Pelicula

@{
    ViewBag.Title = "Detalles de la película";
    var ruta = "../../Images/Caratulas/caratula_" + Model.Id + ".jpg";
}

<style>
    h2 {
        padding-left:10px;
    }
    #caratula {
        float:left;
        border-right: groove;
        padding:5px;
        height:215px;
        width:150px;
    }
    .informacion {
        float: left;
        padding:5px;
    }
    .display-field {
        padding-left:20px;
    }
    #back {
        clear:both;
        text-align: right;
    }

</style>
<h2>Información detallada</h2>
<div id="caratula">
    <img src="@ruta" alt="portada" width="150" height="215"/>
</div>

<div class="informacion">

    <div class="display-label">
         @Html.LabelFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Duracion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Duracion)
    </div>

    <div id="sesiones">
        @foreach(var sesionAct in Model.Sesion){    
                if(DateTime.Now<sesionAct.Fecha && sesionAct.Fecha< DateTime.Now.AddDays(7)){
                    @Html.LabelFor(sesion=>sesionAct.Sala)
                    <div class="display-field">
                         @Html.DisplayFor(sesion=>sesionAct.Sala.Id) 
                         @Html.ActionLink(sesionAct.Fecha.ToString("dd/MM HH:mm"), "Crear", "Reserva", new {id=sesionAct.Id },new {})
                    </div>                  
                }
        }
    </div>
</div>




<p id="back">
    @Html.ActionLink("Back to List", "Index")
</p>

EntrecineWebApp/Views/Pelicula/Detalles.cshtml
@using EntrecineWebApp.Views.Shared
@using EntrecineWebApp.Models
@model EntrecineWebApp.Models.Pelicula

@{
    ViewBag.Title = "Detalles de la película";
    var ruta = "../../Images/Caratulas/caratula_" + Model.Id + ".jpg";
}

<h2>Información detallada</h2>
<div class="movieCaratula">
    <img src="@ruta" alt="Portada"/>
</div>

<div class="movieDetalles">

    <div class="display-label">
         @Html.LabelFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
         @Html.LabelFor(model => model.Duracion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Duracion)
    </div>
    <br />
    <div class="display-label">
         @Html.LabelFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>
    
</div>
<div id ="sesiones">
    
<h3>Próximas Sesiones</h3>
    <table id="tablaSesiones">
        <thead><tr><th style="width:60px;">Sala</th><th>Fecha</th><th>Precio</th></tr></thead>
        <tbody>
        @foreach(var sesionAct in Model.Sesion){    
                if(DateTime.Now<sesionAct.Fecha && sesionAct.Fecha< DateTime.Now.AddDays(7)){
                    <tr onclick="document.location = '/Reserva/Crear/@Html.Encode(sesionAct.Id)';">
                         <td>@Html.Encode(sesionAct.Sala.Id) </td>
                         <td>@Html.Encode(sesionAct.Fecha.ToString("dd/MM/yyyy HH:mm"))</td>       
                         <td>@Html.Encode(sesionAct.PrecioCalculado)€</td>          
                    </tr>
                }
        }
        </tbody>
    </table>
</div>

EntrecineWebApp/Views/Pelicula/Edit.cshtml
@model EntrecineWebApp.Models.Pelicula

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Duracion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Duracion)
            @Html.ValidationMessageFor(model => model.Duracion)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Pelicula/Editar.cshtml
@model EntrecineWebApp.Models.Pelicula

@{
    ViewBag.Title = "Editar Película";
}

<h2>Editar película</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Duracion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Duracion)
            @Html.ValidationMessageFor(model => model.Duracion)
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Pelicula/Index.cshtml
@model IEnumerable<EntrecineWebApp.Models.Pelicula>

@{
    ViewBag.Title = "Editar películas";
}

<h2>Editar Peliculas</h2>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duracion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duracion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", "Pelicula", new { id = item.Id }, new { }) |
            @Html.ActionLink("Detalles", "Detalles", "Pelicula", new { id = item.Id }, new { }) |
        </td>
    </tr>
}

</table>

EntrecineWebApp/Views/Pelicula/IndexCopia.cshtml
@model IEnumerable<EntrecineWebApp.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duracion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duracion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>