EntrecineWebApp/Models/Descuento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrecineWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public Descuento()
        {
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public double Porcentaje { get; set; }
    
        public virtual ICollection<Sesion> Sesion { get; set; }
    }
}

EntrecineWebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntrecineWebApp.Models;
using EntrecineWebApp.Shared;

namespace EntrecineWebApp.Controllers
{
    public class AdminController : Controller
    {
        private EntrecineModelContainer db = new EntrecineModelContainer();

        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(db.PeliculaConjunto.ToList()),RedirectToAction("Index", "Home"));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EntrecineWebApp/Controllers/DescuentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntrecineWebApp.Models;
using EntrecineWebApp.Shared;

namespace EntrecineWebApp.Controllers
{
    public class DescuentoController : Controller
    {
        private EntrecineModelContainer db = new EntrecineModelContainer();

        //
        // GET: /Descuento/
        public ActionResult Index()
        {
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(db.DescuentoConjunto.ToList()), RedirectToAction("Index", "Home"));
        }

        //
        // GET: /Descuento/Crear
        public ActionResult Crear()
        {
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(), RedirectToAction("Index", "Home"));
        }

        //
        // POST: /Descuento/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Descuento descuento)
        {
            if (ModelState.IsValid)
            {
                db.DescuentoConjunto.Add(descuento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(descuento);
        }

        //
        // GET: /Descuento/Edit/5
        public ActionResult Editar(int id = 0)
        {
            Descuento descuento = db.DescuentoConjunto.Find(id);
            if (descuento == null)
            {
                return HttpNotFound();
            }
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(descuento), RedirectToAction("Index", "Home"));
        }

        //
        // POST: /Descuento/Editar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Descuento descuento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(descuento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(descuento);
        }

        //
        // GET: /Descuento/Borrar/5
        public ActionResult Borrar(int id = 0)
        {
            Descuento descuento = db.DescuentoConjunto.Find(id);
            if (descuento == null)
            {
                return HttpNotFound();
            }
            return Seguridad.ComprobarAdministrador(db, User.Identity.Name, View(descuento), RedirectToAction("Index", "Home"));
        }

        //
        // POST: /Descuento/Borrar/5
        [HttpPost, ActionName("Borrar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Descuento descuento = db.DescuentoConjunto.Find(id);
            db.DescuentoConjunto.Remove(descuento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EntrecineWebApp/Views/Descuento/Borrar.cshtml
@model EntrecineWebApp.Models.Descuento

@{
    ViewBag.Title = "Borrar Descuento";
}

<h2>Borrar Descuento</h2>

<h3>¿Seguro que quieres borrar este descuento?</h3>
<fieldset>
    <legend>Descuento</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Porcentaje)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Porcentaje)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Borrar" />
    </p>
}

EntrecineWebApp/Views/Descuento/Crear.cshtml
@model EntrecineWebApp.Models.Descuento

@{
    ViewBag.Title = "Crear Descuento";
}

<h2>Crear descuento</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Descuento</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Porcentaje)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Porcentaje)
            @Html.ValidationMessageFor(model => model.Porcentaje)
        </div>

        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Descuento/Create.cshtml
@model EntrecineWebApp.Models.Descuento

@{
    ViewBag.Title = "Create";
}

<h2>Crear descuento</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Descuento</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Porcentaje)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Porcentaje)
            @Html.ValidationMessageFor(model => model.Porcentaje)
        </div>

        <p>
            <input type="submit" value="Crear" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Descuento/Delete.cshtml
@model EntrecineWebApp.Models.Descuento

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Descuento</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Porcentaje)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Porcentaje)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Borrar" /> |
        @Html.ActionLink("Volver", "Index")
    </p>
}

EntrecineWebApp/Views/Descuento/Edit.cshtml
@model EntrecineWebApp.Models.Descuento

@{
    ViewBag.Title = "Edit";
}

<h2>Edición de descuento</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Descuento</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Porcentaje)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Porcentaje)
            @Html.ValidationMessageFor(model => model.Porcentaje)
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver", "Index","Admin")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Descuento/Editar.cshtml
@model EntrecineWebApp.Models.Descuento

@{
    ViewBag.Title = "Editar Descuento";
}

<h2>Editar de descuento</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Descuento</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Porcentaje)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Porcentaje)
            @Html.ValidationMessageFor(model => model.Porcentaje)
        </div>

        <p>
            <input type="submit" value="Guardar" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntrecineWebApp/Views/Descuento/Index.cshtml
@model IEnumerable<EntrecineWebApp.Models.Descuento>

@{
    ViewBag.Title = "Descuentos";
}

<h2>Descuentos</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Porcentaje)
        </th>
        <th>Opciones</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Porcentaje)%
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", "Descuento", new { id = item.Id }, new { }) |
            @Html.ActionLink("Borrar", "Borrar", "Descuento", new { id = item.Id }, new { })
        </td>
    </tr>
}

</table>